### ISSUE TITLE
Cannot run server

### ISSUE THREAD

**Issue by RaduCorcodel** [wenbowen123/BundleTrack#14]
I have build BundleTrack according to the instructions but when I want to run the server, I am met with this error

```
(base) root@nixie:/homes/corcodel/BundleTrack/BundleTrack# python lf-net-release/run_server.py 
2021-12-20 19:47:03.615220: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-20 19:47:03.615250: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "lf-net-release/run_server.py", line 6, in <module>
    import tensorflow as tf
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python.feature_column import feature_column_lib as feature_column
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_lib.py", line 22, in <module>
    from tensorflow.python.feature_column.feature_column import *
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 147, in <module>
    from tensorflow.python.layers import base
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 20, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/models/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras.models import load_model
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 24, in <module>
    from tensorflow.python.keras._impl.keras.engine import Layer
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras.engine.topology import get_source_inputs
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 51, in <module>
    InputSpec = tf_base_layers.InputSpec
AttributeError: module 'tensorflow.python.layers.base' has no attribute 'InputSpec'
```

If I do ```pip list | grep tensorflow``` I get:

```
tensorflow                      2.6.2    
tensorflow-estimator            2.6.0    
tensorflow-gpu                  1.4.0    
tensorflow-object-detection-api 0.1.1    
tensorflow-tensorboard          0.4.0
```

Any suggestion what I could do? Please ignore the fist error where it complains about not finding the NVIDIA libraries, TF can run without no problem. The issue possibly can be the version of Tensorflow according to this: https://stackoverflow.com/questions/51186116/attributeerror-module-tensorflow-python-layers-layers-has-no-attribute-layer

Thank you,
Radu

EDIT:

OK, so I uninstalled TF and reinstalled an earlier version ```pip install tensorflow==1.15.5```. The server now runs.
I tried to run the first example in NOCS and it runs although it gets a segfault at the end but it's alright I think.

Now for evaluating on the entire NOCS Dataset:

I tried installing an earlier version of Open3D ```pip install open3d=0.11.0.0```, the newest version of Open3D, both give the same error when ran:
```
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /opt/conda/lib/python3.6/site-packages/open3d/open3d_pybind.cpython-36m-x86_64-linux-gnu.so)
```
I ran `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC` to see what's installed in the container and sure enough, 2.7 is not there. The highest is 2.4. So it looks like the most recent version of O3D that works is ```pip install open3d==0.9.0.0```. Then other problems like ```ModuleNotFoundError: No module named 'transformations'```, that's simple to install with `pip install transformations`. There is a directory structure mismatch in the instructions which causes:
```
File "/homes/corcodel/BundleTrack/BundleTrack/scripts/benchmark.py", line 192, in main
    assert len(model_list)>0
AssertionError
```
But that was easy to fix once echoing the path it's searching. What I can't really do now is figure out what directory I need to point to when running ```python scripts/eval_nocs.py --nocs_dir [PAHT TO NOCS]  --results_dir [PATH TO THE RUNNING OUTPUTS]```. Which one exactly is ```--results_dir```?

Thank you.
Radu,

**Comment by wenbowen123** [comment]
Hi, see the sentence before that. `For evaluating on the entire NOCS Dataset, download the converted text pose files from here, and put it like NOCS/gts/real_test_text`  this is the results_dir. 

If you want to get this results by your own, you need to run `python scripts/run_nocs.py ....` for each object instance and aggregate the results.
